# Server port configuration
server:
  port: 8080

## Server profile and DB configuration
spring:
  profiles:
    active: local  # Set the active Spring profile to 'local'
  config:
    import: classpath:application-db.yaml  # Import additional configuration from application-db.yaml
  security:
    oauth2:
      client:
        registration:
          kakao:
            # 오픈되도 괜찮긴 한데 숨길지 말지 논의 필요
            client-id: 8de8b929607ba0d286b7f07a4d19031d
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope: profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
# JWT secret key
jwt:
  secret-key: A8jZz0liqdydjdxW3Ocs8mTwmBZTzkZR

